import { ActivityVoucher } from "@/components/activities/activity-voucher";
import { PrintButton } from "@/components/vouchers/print-button";
import type { ActivityVoucher as ActivityVoucherType } from "@/types/activities";

const sampleVoucher: ActivityVoucherType = {
  supplier: "hotelbeds-activities",
  bookingReference: "102-20736359",
  clientReference: "SAMPLE-HOTLENO-ACT-001",
  confirmationDate: "2026-07-03",
  activityName: "Barcelona City Tour",
  dateFrom: "2026-07-03",
  dateTo: "2026-07-03",
  destinationName: "Barcelona",
  modalityName: "City tour",
  holder: {
    title: "Mr",
    name: "Naif",
    surname: "Alotaibi",
    email: "hotelbeds.tester@hotleno.com",
    telephones: ["+966500000000"],
  },
  paxes: [{ age: 30, name: "Naif", surname: "Alotaibi", type: "AD" }],
  childrenAges: [],
  selectedLanguage: "English",
  selectedSession: "Morning",
  redeemInformation: ["Present this HOTLENO voucher at the activity meeting point."],
  contractRemarks: ["This voucher is generated by HOTLENO for the customer."],
  cancellationPolicies: [{ description: "Cancellation policy available from Hotelbeds Activities response." }],
};

export default function ActivityVoucherSamplePage() {
  return (
    <div className="mx-auto max-w-5xl space-y-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <p className="text-sm font-black text-[#F97316]">Hotelbeds Activities certification</p>
          <h1 className="text-3xl font-black text-[#0F172A]">Activity voucher sample</h1>
        </div>
        <PrintButton />
      </div>
      <ActivityVoucher voucher={sampleVoucher} />
    </div>
  );
}
